-- ═══════════════════════════════════════════════════════════════════════════
--  Freely · messaging + teams setup
--  Paste this whole file into Supabase → SQL Editor → Run. Safe to run again.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Helper: "am I in this team?" ──────────────────────────────────────────
-- SECURITY DEFINER so the team rules can ask this WITHOUT re-triggering
-- themselves (that infinite loop is what makes "create team" fail).
create or replace function public.is_group_member(gid bigint)
returns boolean
language sql security definer stable
set search_path = public
as $$
  select exists (
    select 1 from public.group_members m
    where m.group_id = gid
      and lower(m.email) = lower(auth.jwt() ->> 'email')
  );
$$;

-- ── 1. Profiles — lets people be found by email, and holds their avatar ───
create table if not exists public.profiles (
  id         uuid primary key references auth.users on delete cascade,
  email      text unique not null,
  avatar     text,
  created_at timestamptz default now()
);
alter table public.profiles enable row level security;
drop policy if exists "profiles read"  on public.profiles;
drop policy if exists "profiles write" on public.profiles;
create policy "profiles read"  on public.profiles for select to authenticated using (true);
create policy "profiles write" on public.profiles for all    to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- ── 2. Friend requests — message anyone; one intro note until they accept ─
create table if not exists public.chat_requests (
  id         bigint generated by default as identity primary key,
  from_email text not null,
  to_email   text not null,
  status     text not null default 'pending',
  created_at timestamptz default now(),
  unique (from_email, to_email)
);
alter table public.chat_requests enable row level security;
drop policy if exists "reqs read"   on public.chat_requests;
drop policy if exists "reqs insert" on public.chat_requests;
drop policy if exists "reqs update" on public.chat_requests;
create policy "reqs read"   on public.chat_requests for select to authenticated
  using (lower(auth.jwt() ->> 'email') in (lower(from_email), lower(to_email)));
create policy "reqs insert" on public.chat_requests for insert to authenticated
  with check (lower(auth.jwt() ->> 'email') = lower(from_email));
create policy "reqs update" on public.chat_requests for update to authenticated
  using (lower(auth.jwt() ->> 'email') = lower(to_email));

-- ── 3. Teams ──────────────────────────────────────────────────────────────
create table if not exists public.groups (
  id         bigint generated by default as identity primary key,
  name       text not null,
  icon       text,
  created_by uuid references auth.users on delete cascade,
  created_at timestamptz default now()
);
alter table public.groups enable row level security;
drop policy if exists "groups read"   on public.groups;
drop policy if exists "groups insert" on public.groups;
drop policy if exists "groups update" on public.groups;
drop policy if exists "groups delete" on public.groups;
-- readable by everyone signed in, so you can assign work to a team you are not on
create policy "groups read"   on public.groups for select to authenticated using (true);
create policy "groups insert" on public.groups for insert to authenticated with check (created_by = auth.uid());
create policy "groups update" on public.groups for update to authenticated using (created_by = auth.uid());
create policy "groups delete" on public.groups for delete to authenticated using (created_by = auth.uid());

create table if not exists public.group_members (
  id        bigint generated by default as identity primary key,
  group_id  bigint references public.groups on delete cascade,
  email     text not null,
  added_by  text,
  joined_at timestamptz default now(),
  unique (group_id, email)
);
alter table public.group_members enable row level security;
drop policy if exists "gm read"   on public.group_members;
drop policy if exists "gm insert" on public.group_members;
drop policy if exists "gm delete" on public.group_members;
create policy "gm read"   on public.group_members for select to authenticated using (true);
-- any member may pull someone else in; the creator can seed the first member (themselves)
create policy "gm insert" on public.group_members for insert to authenticated
  with check (
    public.is_group_member(group_id)
    or exists (select 1 from public.groups g where g.id = group_id and g.created_by = auth.uid())
  );
create policy "gm delete" on public.group_members for delete to authenticated
  using (
    lower(email) = lower(auth.jwt() ->> 'email')
    or exists (select 1 from public.groups g where g.id = group_id and g.created_by = auth.uid())
  );

-- ── 4. Messages — 1:1 DMs and team chats share one table ─────────────────
create table if not exists public.messages (
  id              bigint generated by default as identity primary key,
  sender_id       uuid not null default auth.uid(),
  sender_email    text not null,
  recipient_email text,
  group_id        bigint,
  body            text not null,
  read            boolean default false,
  created_at      timestamptz default now()
);
-- heal an older DM-only table: team chats have no recipient, so that column must allow NULL
alter table public.messages add column if not exists group_id bigint;
alter table public.messages add column if not exists read boolean default false;
alter table public.messages alter column recipient_email drop not null;

alter table public.messages enable row level security;
drop policy if exists "dm read"   on public.messages;
drop policy if exists "dm send"   on public.messages;
drop policy if exists "dm update" on public.messages;
create policy "dm read" on public.messages for select to authenticated
  using (
    lower(auth.jwt() ->> 'email') in (lower(sender_email), lower(coalesce(recipient_email,'')))
    or (group_id is not null and public.is_group_member(group_id))
  );
create policy "dm send" on public.messages for insert to authenticated
  with check (
    sender_id = auth.uid()
    and lower(sender_email) = lower(auth.jwt() ->> 'email')
    and (group_id is null or public.is_group_member(group_id))
  );
create policy "dm update" on public.messages for update to authenticated
  using (lower(auth.jwt() ->> 'email') = lower(coalesce(recipient_email,'')));

-- ── 5. Live updates (chat appearing without a refresh) ───────────────────
do $$
declare t text;
begin
  foreach t in array array['messages','groups','group_members','chat_requests'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

-- ── 6. Tell the API about all of the above ───────────────────────────────
notify pgrst, 'reload schema';
