-- ═══════════════════════════════════════════════════════════════════════════
--  Freely · database setup
--  Paste this whole file into Supabase → SQL Editor → Run. Safe to run again,
--  and safe to run on a database that already has data — it only ever adds.
--
--  Order matters here: every table and column is created FIRST, then the
--  helper functions that read them, then the security rules. (Postgres checks
--  a function's body the moment you create it, so a function written before
--  its column exists fails with "column ... does not exist".)
--
--  The rules it installs:
--   · You can only see a team you were invited to — as a full member, or as a
--     guest who may assign work to it but not read its chat.
--   · Teammates can message each other directly, no friend request needed.
--   · A task assigned to you is visible to you even if its list was never
--     shared with you, and it shows up under "Assigned to me".
--   · A list can be shared view-only: they can read it but not change, add or delete.
--   · Everyone sharing a list sees who a task is assigned to — unless the
--     assigner marks it private, and then only the assignee can see it.
--   · Habits keep the order you drag them into, on every device.
--   · Each list name exists once per person (the app saves lists by name).
--   · You can see the email/avatar only of people you're connected to (a shared list, a team, a chat).
--   · Sent messages can't be rewritten; tasks can't change owner; only a list's owner creates or
--     changes its shares.
-- ═══════════════════════════════════════════════════════════════════════════


-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  STEP 1 · Tables and columns                                          ║
-- ╚═══════════════════════════════════════════════════════════════════════╝

-- Profiles — lets people be found by email, and holds their avatar
create table if not exists public.profiles (
  id         uuid primary key references auth.users on delete cascade,
  email      text unique not null,
  avatar     text,
  created_at timestamptz default now()
);

-- Friend requests — message anyone; one intro note until they accept
create table if not exists public.chat_requests (
  id         bigint generated by default as identity primary key,
  from_email text not null,
  to_email   text not null,
  status     text not null default 'pending',
  created_at timestamptz default now(),
  unique (from_email, to_email)
);

-- Teams
create table if not exists public.groups (
  id         bigint generated by default as identity primary key,
  name       text not null,
  icon       text,
  created_by uuid references auth.users on delete cascade,
  created_at timestamptz default now()
);

create table if not exists public.group_members (
  group_id  bigint references public.groups on delete cascade,
  email     text not null,
  added_by  text,
  role      text not null default 'member',
  joined_at timestamptz default now(),
  unique (group_id, email)
);
-- 'member' = full teammate (reads the team chat) · 'assigner' = guest who may only assign work.
-- Added separately so an older table without this column is healed rather than skipped.
alter table public.group_members add column if not exists role text not null default 'member';

-- Messages — 1:1 DMs and team chats share one table
create table if not exists public.messages (
  id              bigint generated by default as identity primary key,
  sender_id       uuid not null default auth.uid(),
  sender_email    text not null,
  recipient_email text,
  group_id        bigint,
  body            text not null,
  read            boolean default false,
  created_at      timestamptz default now()
);
-- heal an older DM-only table: team chats have no recipient, so that column must allow NULL
alter table public.messages add column if not exists group_id bigint;
alter table public.messages add column if not exists read boolean default false;
alter table public.messages alter column recipient_email drop not null;

-- Private assignment: hidden from the rest of the list, visible to the assignee
alter table public.tasks add column if not exists assign_private boolean default false;

-- View-only sharing: they see the list, they can't change it. Older rows have no value → editable.
alter table public.folder_shares add column if not exists can_edit boolean default true;

-- Habit order. Without it the order you drag habits into only survived by accident.
alter table public.habits add column if not exists position double precision;

-- One row per list name per person. The app saves lists by upserting on (user_id, name), which needs
-- this index. Any accidental duplicates are removed first (keeping one), or the index can't be built.
delete from public.categories a
  using public.categories b
  where a.user_id = b.user_id and a.name = b.name and a.ctid < b.ctid;
create unique index if not exists categories_user_name_key on public.categories (user_id, name);


-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  STEP 2 · Helper functions                                            ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
-- SECURITY DEFINER so the team rules can ask these WITHOUT re-triggering
-- themselves (that infinite loop is what makes "create team" fail).

-- full member: in the team, reads the team chat
create or replace function public.is_group_member(gid bigint)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.group_members m
    where m.group_id = gid
      and lower(m.email) = lower(auth.jwt() ->> 'email')
      and coalesce(m.role, 'member') = 'member'
  );
$$;

-- linked at all: member OR a guest invited only to assign work to the team
create or replace function public.is_group_linked(gid bigint)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.group_members m
    where m.group_id = gid
      and lower(m.email) = lower(auth.jwt() ->> 'email')
  );
$$;

-- is this task assigned to me? (assigned_to is a comma-separated email list)
create or replace function public.is_assigned_to_me(assigned text)
returns boolean language sql stable set search_path = public as $$
  select lower(auth.jwt() ->> 'email') = any (
    string_to_array(replace(lower(coalesce(assigned, '')), ' ', ''), ',')
  );
$$;


-- are we connected? — sharing a list either way, in a team together, or in a conversation.
-- Decides whose profile (email + avatar) you may see. Before this, every signed-in account could read
-- every other account's email.
create or replace function public.is_connected_to(other_id uuid, other_email text)
returns boolean language sql security definer stable set search_path = public as $$
  select
    other_id = auth.uid()
    or exists (select 1 from public.folder_shares fs
               where (fs.owner_id = auth.uid() and lower(fs.shared_with_email) = lower(other_email))
                  or (fs.owner_id = other_id and lower(fs.shared_with_email) = lower(auth.jwt() ->> 'email')))
    or exists (select 1 from public.group_members a
               join public.group_members b on a.group_id = b.group_id
               where lower(a.email) = lower(auth.jwt() ->> 'email') and lower(b.email) = lower(other_email))
    or exists (select 1 from public.messages m
               where (lower(m.sender_email) = lower(auth.jwt() ->> 'email') and lower(coalesce(m.recipient_email, '')) = lower(other_email))
                  or (lower(coalesce(m.recipient_email, '')) = lower(auth.jwt() ->> 'email') and lower(m.sender_email) = lower(other_email)))
    or exists (select 1 from public.chat_requests r
               where (lower(r.from_email) = lower(auth.jwt() ->> 'email') and lower(r.to_email) = lower(other_email))
                  or (lower(r.to_email) = lower(auth.jwt() ->> 'email') and lower(r.from_email) = lower(other_email)));
$$;

-- a task's owner never changes (nothing in the app does it) — so nobody can take someone else's task
create or replace function public.keep_task_owner()
returns trigger language plpgsql as $$
begin
  if new.user_id is distinct from old.user_id then
    raise exception 'A task''s owner can''t be changed';
  end if;
  return new;
end $$;


-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  STEP 3 · Security rules                                              ║
-- ╚═══════════════════════════════════════════════════════════════════════╝

-- Your own notes, canvas, habits and lists ──────────────────────────────────
-- The app saves these by changing only the rows that changed (insert or update), where it used to
-- delete everything and re-insert. That needs update permission, so it is granted here explicitly —
-- for your own rows only. Added alongside any existing rules; it never opens anyone else's data.
do $$
declare t text;
begin
  foreach t in array array['notes','canvas_notes','habits','categories'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "own rows" on public.%I', t);
    execute format('create policy "own rows" on public.%I for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())', t);
  end loop;
end $$;

-- Profiles ────────────────────────────────────────────────────────────────
alter table public.profiles enable row level security;
drop policy if exists "profiles read"  on public.profiles;
drop policy if exists "profiles write" on public.profiles;
-- only people you are connected to (see is_connected_to) — not every account on Freely
create policy "profiles read"  on public.profiles for select to authenticated using (public.is_connected_to(id, email));
create policy "profiles write" on public.profiles for all    to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- Friend requests ─────────────────────────────────────────────────────────
alter table public.chat_requests enable row level security;
drop policy if exists "reqs read"   on public.chat_requests;
drop policy if exists "reqs insert" on public.chat_requests;
drop policy if exists "reqs update" on public.chat_requests;
create policy "reqs read"   on public.chat_requests for select to authenticated
  using (lower(auth.jwt() ->> 'email') in (lower(from_email), lower(to_email)));
create policy "reqs insert" on public.chat_requests for insert to authenticated
  with check (lower(auth.jwt() ->> 'email') = lower(from_email));
create policy "reqs update" on public.chat_requests for update to authenticated
  using (lower(auth.jwt() ->> 'email') = lower(to_email));

-- Teams ───────────────────────────────────────────────────────────────────
alter table public.groups enable row level security;
drop policy if exists "groups read"   on public.groups;
drop policy if exists "groups insert" on public.groups;
drop policy if exists "groups update" on public.groups;
drop policy if exists "groups delete" on public.groups;
-- a team is NOT public: you see it only once someone invites you to it
create policy "groups read"   on public.groups for select to authenticated
  using (created_by = auth.uid() or public.is_group_linked(id));
create policy "groups insert" on public.groups for insert to authenticated with check (created_by = auth.uid());
create policy "groups update" on public.groups for update to authenticated using (created_by = auth.uid());
create policy "groups delete" on public.groups for delete to authenticated using (created_by = auth.uid());

alter table public.group_members enable row level security;
drop policy if exists "gm read"   on public.group_members;
drop policy if exists "gm insert" on public.group_members;
drop policy if exists "gm delete" on public.group_members;
create policy "gm read" on public.group_members for select to authenticated
  using (
    public.is_group_linked(group_id)
    or exists (select 1 from public.groups g where g.id = group_id and g.created_by = auth.uid())
  );
-- any full member may pull someone in (guests may not); the creator seeds the first row
create policy "gm insert" on public.group_members for insert to authenticated
  with check (
    public.is_group_member(group_id)
    or exists (select 1 from public.groups g where g.id = group_id and g.created_by = auth.uid())
  );
create policy "gm delete" on public.group_members for delete to authenticated
  using (
    lower(email) = lower(auth.jwt() ->> 'email')
    or public.is_group_member(group_id)
    or exists (select 1 from public.groups g where g.id = group_id and g.created_by = auth.uid())
  );

-- Messages ────────────────────────────────────────────────────────────────
alter table public.messages enable row level security;
drop policy if exists "dm read"   on public.messages;
drop policy if exists "dm send"   on public.messages;
drop policy if exists "dm update" on public.messages;
create policy "dm read" on public.messages for select to authenticated
  using (
    lower(auth.jwt() ->> 'email') in (lower(sender_email), lower(coalesce(recipient_email,'')))
    or (group_id is not null and public.is_group_member(group_id))   -- guests do not read team chat
  );
create policy "dm send" on public.messages for insert to authenticated
  with check (
    sender_id = auth.uid()
    and lower(sender_email) = lower(auth.jwt() ->> 'email')
    and (group_id is null or public.is_group_member(group_id))
  );
create policy "dm update" on public.messages for update to authenticated
  using (lower(auth.jwt() ->> 'email') = lower(coalesce(recipient_email,'')));

-- Assignment ──────────────────────────────────────────────────────────────
-- Added ALONGSIDE your existing task rules, so nothing you can see today disappears.
drop policy if exists "tasks assigned to me" on public.tasks;
create policy "tasks assigned to me" on public.tasks for select to authenticated
  using (public.is_assigned_to_me(assigned_to));

-- ...and you can tick off work that was handed to you
drop policy if exists "assignees update" on public.tasks;
create policy "assignees update" on public.tasks for update to authenticated
  using (public.is_assigned_to_me(assigned_to));

-- Someone you shared a list with can edit the work in it — including handing a task
-- to someone else. (The share UI only ever offers "Edit & add" or "+ delete", so every
-- share is an editing share.) Without this, an assignment made by a collaborator looks
-- saved on their screen but is silently dropped, and the new assignee sees nothing.
drop policy if exists "collaborators edit shared tasks" on public.tasks;
create policy "collaborators edit shared tasks" on public.tasks for update to authenticated
  using (
    exists (select 1 from public.folder_shares fs
            where fs.owner_id = tasks.user_id and fs.folder = tasks.tag
              and lower(fs.shared_with_email) = lower(auth.jwt() ->> 'email')
              and coalesce(fs.can_edit, true))
  )
  with check (
    exists (select 1 from public.folder_shares fs
            where fs.owner_id = tasks.user_id and fs.folder = tasks.tag
              and lower(fs.shared_with_email) = lower(auth.jwt() ->> 'email')
              and coalesce(fs.can_edit, true))
  );

-- ...and add new work to that shared list (the app files it under the list's owner)
drop policy if exists "collaborators add to shared lists" on public.tasks;
create policy "collaborators add to shared lists" on public.tasks for insert to authenticated
  with check (
    user_id = auth.uid()
    or exists (select 1 from public.folder_shares fs
               where fs.owner_id = tasks.user_id and fs.folder = tasks.tag
                 and lower(fs.shared_with_email) = lower(auth.jwt() ->> 'email')
              and coalesce(fs.can_edit, true))
  );

-- RESTRICTIVE: applies on top of every other rule. A private assignment is
-- visible only to the task's owner and the people it is assigned to.
drop policy if exists "private assignments stay private" on public.tasks;
create policy "private assignments stay private" on public.tasks
  as restrictive for select to authenticated
  using (
    coalesce(assign_private, false) = false
    or user_id = auth.uid()
    or public.is_assigned_to_me(assigned_to)
  );


-- Hardening ────────────────────────────────────────────────────────────────
-- Messages: the only thing anyone may change on a message after it's sent is whether it's been read.
-- (The recipient's "mark read" rule used to allow rewriting the text — or who it was from.)
revoke update on public.messages from authenticated;
grant update (read) on public.messages to authenticated;

-- Friend requests: only the answer (status) can change, never who it's from or to.
revoke update on public.chat_requests from authenticated;
grant update (status) on public.chat_requests to authenticated;

-- Tasks keep their owner. Someone a task is assigned to can tick it off and edit it, not take it.
drop trigger if exists keep_task_owner on public.tasks;
create trigger keep_task_owner before update on public.tasks
  for each row execute function public.keep_task_owner();

-- Shares: only the list's OWNER creates or changes a share, so a view-only person can't upgrade
-- themselves and a collaborator can't pass your list on. The invited person may still remove their own
-- share (leaving the list). RESTRICTIVE, so this holds whatever other share rules exist.
drop policy if exists "shares: only the owner creates" on public.folder_shares;
create policy "shares: only the owner creates" on public.folder_shares
  as restrictive for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists "shares: only the owner changes" on public.folder_shares;
create policy "shares: only the owner changes" on public.folder_shares
  as restrictive for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
drop policy if exists "shares: owner or invitee removes" on public.folder_shares;
create policy "shares: owner or invitee removes" on public.folder_shares
  as restrictive for delete to authenticated
  using (owner_id = auth.uid() or lower(shared_with_email) = lower(auth.jwt() ->> 'email'));


-- ╔═══════════════════════════════════════════════════════════════════════╗
-- ║  STEP 4 · Live updates, then tell the API about everything            ║
-- ╚═══════════════════════════════════════════════════════════════════════╝
do $$
declare t text;
begin
  foreach t in array array['messages','groups','group_members','chat_requests'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

notify pgrst, 'reload schema';
